### PR TITLE
Add exploration report about selector syntax

### PR DESCRIPTION
**Pull request by vmx**
This exploration report was originally a PR. It got converted into an
exploration report in order to preserve all the useful information it
contains.

It contains a few comments that a not necessarily needed, but the nice
thing is that my script created this output without manual interference.

If someone feels like cleaning things up, feel free to do so.

### CODE REVIEW

**Review by rvagg — APPROVED** [review]
a shame to drop this one for now, but hopefully we can get back to it soon

**Comment by vmx** [comment]
In case someone wants to do such an export, I've published the script here: https://github.com/vmx/export_issues

**Comment by warpfork** [comment]
Do you think we should perhaps put that text you open this PR with ("This exploration report was originally a PR. It got converted into an exploration report in order to preserve all the useful information it contains. [...]", etc) into the top of the file that's generated?  I think it might help someone finding that file to understand what's up.

**Review by warpfork — APPROVED** [review]

**Review by qasemsherfi — APPROVED** [review]

**Comment by vmx** [comment]
@warpfork Good idea. Please re-review.

**Comment by warpfork** [comment]
:+1:

**Pull request merged**
