### PR TITLE
Cardinality concept intro

### PR DESCRIPTION
**Pull request by warpfork**
Add 'concepts' folder; Introduce cardinality.

This is still pretty brief, but it's been mentioned elsewhere that since this is a recurring theme, we should introduce it somewhere on its own rather than just in passing in various places.

I'm guessing we'll end up with some other things to populate this 'concepts' folder later as well.

### CODE REVIEW

**Review by vmx — APPROVED** [review]
Nice. This reads good and clear to me.

**Comment by rvagg** [comment]
The content is fine, but ... Other concepts are addressed in the README already, so maybe they should be pulled out into the "concepts" directory, or maybe this should go into the README? If it ends up in files other than the README then somewhere needs to spell out that what's in the "concepts" directory is not "spec" material. Also, how do the merge rules in #122 apply to concepts (and the README too I guess?).

**Comment by warpfork** [comment]
I think I'll merge this so the content gets on master, and then agree we should do another pass on the readmes and such to see of other things might belong in this dir (or this content should settle elsewhere and we can drop this dir again).

I'd propose a rule of thumb that we put stuff that's underlying design reasoning and concepts rather than particulars of design; meta-rationale, if you will.

**Comment by rvagg** [comment]
@warpfork we have a new directory layout now and "concepts" are alongside specs now but are also clearly labelled as such. See https://github.com/ipld/specs/pull/128 for a rearrangement of this to fit into the new layout.

**Pull request merged**
