### PR TITLE
Remove selector types which we haven't agreed on yet

### PR DESCRIPTION
**Pull request by vmx**
It's misleading to have detailed information about selector types although
they will likely still change a lot. Hence removing them for now until
we have an agreed upon replacement.

### CODE REVIEW

**Review by Stebalien — COMMENTED** [review]
This has a lot of useful information on what a selector is and how we think they should operate. Can we move this section to a new document (something like selector-exploration) or an issue (and link it)?

**Comment by vmx** [comment]
@Stebalien Done: https://github.com/ipld/specs/issues/94

**Comment by Stebalien** [comment]
That issue currently refers to some non-existent "above" section.

**Comment by vmx** [comment]
@Stebalien fixed.

**Review by Stebalien — APPROVED** [review]

**Review by warpfork — APPROVED** [review]

**Pull request merged**
